site_name: Seguridad en sistemas del curso de especialista en ciberseguridad
site_url: https://jogonar-rgb.github.io/Ciberseguridad_2025_2026/


theme:
  name: material
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - toc.integrate
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    
  palette:
      - scheme: default
        primary: light green
        toggle:
          icon: material/toggle-switch-off-outline
          name: Cambiar a modo oscuro
      - scheme: slate
        primary: teal
        toggle:
          icon: material/toggle-switch
          name: Cambiar a modo normal
  plugins:
    - mkdocs-video:
        mark: "vid"
    - search:
      lang: es

      
markdown_extensions: 
  - admonition
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.caret   
  - pymdownx.critic 
  - pymdownx.details 
  - attr_list
  - md_in_html
  - footnotes

nav:
  - Warm up:
    - warm/index.md
    - Entornos Linux: warm/EntLinux.md
    - Ejercicios propuestos Linux: warm/Ej_Linux.md
    - Entornos Windows: warm/EntWin.md
    - Ejercicios propuestos Windows: warm/Ej_Win.md
    - Webgrafía: warm/webgrafia.md
